## 1. Liste Metodları

In [51]:
def not_islemleri():
    notlar = [85, 92, 76, 92, 100, 76, 85, 92]
    
    new_list = list(set(notlar))

    print(new_list)
    print(f"En yüksek not: {max(notlar)}")
    print(f"En düşük not: {min(notlar)}")
    print(f"Sıralı: {sorted(new_list)}")

not_islemleri()

[100, 92, 85, 76]
En yüksek not: 100
En düşük not: 76
Sıralı: [76, 85, 92, 100]


## 2. Armstrong Sayısı

In [52]:
def armstrong_kontrol():
    sayi = int(input("Bir sayı giriniz: "))
    toplam = sum(int(h)**3 for h in str(sayi))

    if toplam == sayi:
        print("Sayınız armstrong sayıdır.")
    else:
        print("Sayınız armstrog sayı değildir.")

armstrong_kontrol()

Bir sayı giriniz:  407


Sayınız armstrong sayıdır.


## 3. Küme İşlemleri

In [53]:
def kume_islemleri():
    A = {"Python", "R", "SQL", "Java"}
    B = {"C++", "Python", "JavaScript", "SQL"}

    print("Ortak: ", A & B)
    print("Sadece A kümesinde olanlar: ", A - B)
    print("Alfabetik olarak birleşimleri: ", sorted(A | B))

kume_islemleri()

Ortak:  {'Python', 'SQL'}
Sadece A kümesinde olanlar:  {'R', 'Java'}
Alfabetik olarak birleşimleri:  ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


## 4. Modüller

In [54]:
import random, statistics

sayilar = [random.randint(1, 100) for _ in range(10)]

print("Sayılar: ", sayilar)
print("Ortalama: ", statistics.mean(sayilar))
print("Standart sapma: ", statistics.pstdev(sayilar))

Sayılar:  [54, 93, 30, 1, 3, 37, 14, 92, 66, 29]
Ortalama:  41.9
Standart sapma:  31.85105963700423


## 5. Fonskiyonlar

In [55]:
def kelime_sayaci(metin):
    kelime_sayisi = metin.split()
    toplam_kelime = len(kelime_sayisi)
    en_uzun_kelime = max(kelime_sayisi, key = len)
    en_çok_kelime = max(set(kelime_sayisi), key = kelime_sayisi.count)

    print("Toplam kelime sayısı: ", toplam_kelime)
    print("En uzun kelime: ", en_uzun_kelime)
    print("En sık geçen kelime: ", en_çok_kelime)

kelime_sayaci("TechCareer Veri Bilimi Yaz Kampı çok ama çok verimli ilerliyor")

Toplam kelime sayısı:  10
En uzun kelime:  TechCareer
En sık geçen kelime:  çok


## 6. Gömülü Fonksiyonlar

In [56]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

ciftler = list(filter(lambda x: x%2 == 0, sayilar))
kareleri = list(map(lambda x: x**2, ciftler))
siralama = sorted(kareleri, reverse = True)

print("Çiftler:", ciftler)
print("Kareler:", kareleri)
print("Azalan kareler:", siralama)

Çiftler: [12, 18, 24, 16]
Kareler: [144, 324, 576, 256]
Azalan kareler: [576, 324, 256, 144]


## 7. Lambda İfadeleri

In [57]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

print(sorted(kelimeler, key = lambda x: len(x)))

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


## 8. Metodlar

In [58]:
def rakam_toplam(metin):
    islem = sum(int(c) for c in metin if c.isdigit())
    print("Sayılar toplamı: ", islem)

rakam_toplam("abc8d3ef9")

Sayılar toplamı:  20


## 9. Numpy 1

In [59]:
import numpy as np

numpy_dizisi = np.random.randint(0,50,10)
print("Dizi: ", numpy_dizisi)
print("Ortalama: ", numpy_dizisi.mean())
print("Standart sapma: ", numpy_dizisi.std())
print("En büyük değer: ", numpy_dizisi.max())

Dizi:  [41  6 15 13  4 17 12 11 29 37]
Ortalama:  18.5
Standart sapma:  12.118168178400563
En büyük değer:  41


## 10. Numpy 2

In [60]:
matris = np.random.rand(5,5)
print("Matris:\n", matris)
print(matris.mean(axis = 0))

binary = np.where(matris > 0.5 , 1, 0)
print("Binary matris:\n", binary)

Matris:
 [[0.38700084 0.51831259 0.39003514 0.09900672 0.9500482 ]
 [0.38122211 0.52767196 0.99782712 0.99671686 0.68303755]
 [0.17241278 0.1238638  0.30790227 0.05930681 0.57953843]
 [0.6367136  0.50781489 0.52536204 0.82131249 0.02907944]
 [0.61177445 0.75674182 0.78289467 0.65381774 0.96982371]]
[0.43782476 0.48688101 0.60080425 0.52603213 0.64230547]
Binary matris:
 [[0 1 0 0 1]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [1 1 1 1 0]
 [1 1 1 1 1]]
